### ISSUE TITLE
Better default install location

### ISSUE THREAD

**Issue by thaljef** [serverdensity/puppet-serverdensity#39]
By default, it seems the agent and related files are installed into a directory at `/usr/bin/sd-agent`. Typically, *nix platforms do not have subdirectories under `/usr/bin` because `bin` directories usually only contain executables. The [Filesystem Hierarchy Standard](https://www.samba.org/~cyeoh/pub/fhs-2.3.pdf) actually insists on it.

A better location might be `/opt/sd-agent`.

**Comment by carlosperello** [comment]
Latest agent release (2.0.0) is using now /usr/share/python/sd-agent
